# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address',
            new_name='street_address2',
        ),
    ]
